#!/usr/bin/env bash

swaylock \
    --image ~/.config/sway/wallpaper.png \
    --scaling fill \
    --indicator-radius 100 \
    --indicator-thickness 10 \
    --ring-color 383c4a \
    --key-hl-color 5294e2 \
    --inside-color 00000088 \
    --separator-color 00000000 \
    --text-color ffffff
