#!/usr/bin/env bash

FG_COLOR="#bbbbbb"
BG_COLOR="#111111"
HLFG_COLOR="#111111"
HLBG_COLOR="#bbbbbb"
BORDER_COLOR="#222222"

ROFI_OPTIONS=(-theme ~/.config/rofi/power-profiles.rasi)

enable_confirmation=false
preferred_launcher="rofi"

launcher_list=(rofi zenity)
function check_launcher() {
  if [[ ! "${launcher_list[@]}" =~ (^|[[:space:]])"$1"($|[[:space:]]) ]]; then
    echo "Supported launchers: ${launcher_list[*]}"
    exit 1
  else
    i=1
    launcher_list=($(for l in "$1" "${launcher_list[@]}"; do printf "%i %s\n" "$i" "$l"; let i+=1; done \
      | sort -uk2 | sort -nk1 | cut -d' ' -f2- | tr '\n' ' '))
  fi
}

while getopts "hcp:" option; do
  case "${option}" in
    h) echo "Usage: $(basename "$0") [-h] [-c] [-p name]"; exit 0 ;;
    c) enable_confirmation=true ;;
    p) preferred_launcher="${OPTARG}"; check_launcher "${preferred_launcher}" ;;
    *) exit 1 ;;
  esac
done

function command_exists() {
  command -v "$1" &> /dev/null 2>&1
}

if ! command_exists systemctl ; then
  exit 1
fi

typeset -A menu

menu=(
  [" Performance"]="powerprofilesctl set performance"
  [" Balanced"]="powerprofilesctl set balanced"
  [" Power Saver"]="powerprofilesctl set power-saver"
  [" Cancel"]=""
)

menu_nrows=${#menu[@]}
menu_confirm=""

launcher_exe=""
launcher_options=""
rofi_colors=""

function prepare_launcher() {
  if [[ "$1" == "rofi" ]]; then
    rofi_colors=(-bc "${BORDER_COLOR}" -bg "${BG_COLOR}" -fg "${FG_COLOR}" \
        -hlfg "${HLFG_COLOR}" -hlbg "${HLBG_COLOR}")
    launcher_exe="rofi"
    launcher_options=(-dmenu -i -lines "${menu_nrows}" -p "${ROFI_TEXT}" \
        "${rofi_colors}" "${ROFI_OPTIONS[@]}")
  elif [[ "$1" == "zenity" ]]; then
    launcher_exe="zenity"
    launcher_options=(--list --title="Power Profiles" --text="Set Profiles:" --column= --hide-header)
  fi
}

for l in "${launcher_list[@]}"; do
  if command_exists "${l}" ; then
    prepare_launcher "${l}"
    break
  fi
done

if [[ -z "${launcher_exe}" ]]; then
  exit 1
fi

launcher=(${launcher_exe} "${launcher_options[@]}")
selection="$(printf '%s\n' "${!menu[@]}" | sort | "${launcher[@]}")"

if [[ $? -eq 0 && ! -z ${selection} ]]; then
  swaymsg "exec ${menu[${selection}]}"
fi
