#!/usr/bin/env bash

PICTURE="/tmp/xsecurelock-bg.png"
BLUR="0x8"

scrot -z "$PICTURE"
magick "$PICTURE" -blur "$BLUR" "$PICTURE"

export XSECURELOCK_SAVER="$HOME/.config/i3/scripts/blur-saver"
xsecurelock 2>/dev/null

rm -f "$PICTURE"
